config/routes.rb
Rails.application.routes.draw do

  root to: 'feed#index'
  post '/', to: 'feed#create', as: :search
  get '/results', to: 'feed#show', as: :results
  post '/', to: 'feed#like_post', as: :like_post
  post '/', to: 'feed#unlike_post', as: :unlike_post
  get '/auth/instagram', as: :login
  get '/auth/instagram/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: :logout
  get '/:username', to: 'dashboard#show', as: :dashboard
end

app/models/media.rb
class Media < ActiveRecord::Base
  attr_reader :service

  def self.service(user)
    @service ||= InstagramService.new(user)
  end

  def self.user_posts(user)
    service(user).user_posts
  end

  def self.search_by_tag(user, tag)
    service(user).search_by_tag(tag)
  end

  def self.like_post(user, id)
    service(user).like_post(id)
  end

  def self.unlike_post(user, id)
    service(user).unlike_post(id)
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  def self.find_or_create(auth_info)
    user = User.find_or_create_by(uid: auth_info[:uid])
    user.update_attributes(
      username:           auth_info.extra.raw_info.username,
      name:               auth_info.extra.raw_info.full_name,
      bio:                auth_info.extra.raw_info.bio,
      profile_picture:    auth_info.extra.raw_info.profile_picture,
      website:            auth_info.extra.raw_info.website,
      oauth_token:        auth_info.credentials.token,
      oauth_token_secret: auth_info.credentials.secret
    )
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def show
    if current_user
      @user_posts = Media.user_posts(current_user)
    end
  end
end

app/controllers/feed_controller.rb
class FeedController < ApplicationController

  def index
    if current_user
      @recent_feed = Media.search_by_tag(current_user, 'berner')
    end
  end

  def create
    @recent_feed = Media.search_by_tag(current_user, params[:q])
    redirect_to results_path(params)
  end

  def show
    @recent_feed = Media.search_by_tag(current_user, params[:q])
  end

  def like_post
    @like_post = Media.like_post(current_user, id)
  end

  def unlike_post
    @unlike_post = Media.unlike_post(current_user, id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_or_create(auth_info)
    if user
      Instagram.authorize_url(:redirect_uri => ENV['callback_url'])
      session[:user_id] = user.id
      redirect_to dashboard_path(user.username)
    else
      redirect_to root_path
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end

  private

  def auth_info
    request.env["omniauth.auth"]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def login_logout_path
    if current_user
      link_to "logout", logout_path
    end
  end

  def user_profile_path
    if current_user
      link_to "#{current_user.username}", dashboard_path(current_user.username)
    end
  end
end

app/views/dashboard/_user_profile.html.erb
<br>
  <br>
    <div class="row">
      <div class="col s4 offset-m1 round"><%= image_tag current_user.profile_picture %></div>
      <div class="col s7">
        <h3 class="text-grey darken-1" id="user-profile"> <%= current_user.username %> </h3>
        <p><%= current_user.name %> - <%= current_user.bio %></p>
        <a href='<%= current_user.website%>' target="_blank"><%= current_user.website %> </a>
      </div>
    </div>
    <br>
  <br>
<br>

app/views/dashboard/_user_recent_posts.html.erb
<div class="row">
  <% @user_posts.each do |post| %>
    <div class="col s4">
      <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
          <img class="activator" id="dashboard-user-photos" src="<%= post.images.thumbnail.url %>" >
        </div>
        <div class="card-reveal" id="<%= post.caption.text.parameterize %>">
          <span class="card-title grey-text text-darken-4"><%= post.user.username %><i class="material-icons right">close</i></span>
          <p>Favorites: <%= post.likes[:count] %></p>
          <p><a href='<%= post.user.username %>'><%= post.user.username %> </a><%= post.caption.text %></p>
          <p>Comments: <%= post.comments[:count]%></p>
          <a href='#'>Like</a> |
          <a href='#'>Unlike</a>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/dashboard/show.html.erb
<div class="container">
  <% if current_user %>
    <%= render "user_profile" %>
    <%= render "user_recent_posts" %>
  <% else %>
    <%= render "layouts/login_prompt" %>
  <% end %>
</div>

app/views/feed/_recent_feed.html.erb
<div class="row">
  <% @recent_feed.each do |post| %>
    <div class="col s4">
      <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
          <img class="activator" id="dashboard-user-photos" src="<%= post.images.thumbnail.url %>" >
        </div>
        <div class="card-reveal" id="<%= post.caption.text.parameterize %>">
          <span class="card-title grey-text text-darken-4"><%= post.user.username %><i class="material-icons right">close</i></span>
          <p>Favorites: <%= post.likes[:count] %></p>
          <p><a href='<%= post.user.username %>'><%= post.user.username %> </a><%= post.caption.text %></p>
          <p>Comments: <%= post.comments[:count] %></p>
          <br>
        <a href='<% like_post_path(post.id) %>'>Like</a> |
        <a href='<% like_post_path(post.id) %>'>Unlike</a>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/feed/_search_form.html.erb
<br>
<br>
<div class="row">
  <div class="center">
    <div class="col s8 offset-m2">
      <nav class="search white z-depth-0" id="search-field">
        <%= form_tag("/", class: "form-inline", method: "post") do %>
          <div class="form-group input-field">
            <span id="#seach-box"><%= text_field_tag :q, nil, placeholder: 'Enter search term...'%></span>
            <%= submit_tag "Search", class: "hidden" %>
          </div>
        <% end %>
      </nav>
    </div>
  </div>
</div>
<br>

app/views/feed/index.html.erb
<div class="container">
  <% if current_user %>
    <%= render "search_form" %>
    <%= render "recent_feed" %>
  <% else %>
    <%= render "layouts/login_prompt" %>
  <% end %>
</div>

app/views/feed/show.html.erb
<div class="container">
  <% if current_user %>
    <%= render "search_form" %>
    <%= render "recent_feed" %>
  <% else %>
    <%= render "layouts/login_prompt" %>
  <% end %>
</div>

app/views/layouts/_login_prompt.html.erb
<div class="row center-align">
  <div class="col s12 greeting" >
    <br/>
    <div class="col s6">
      <img src="http://cdn.redmondpie.com/wp-content/uploads/2013/04/iOS-Screenshot-20130420-195130-02.png" alt="MDN">
    </div>
    <div class="col s6">
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <h4 class="black-text" id="login-prompt">Start Your Adventure</h4>
      <br/>
      <%= link_to "login", login_path, class: "waves-effect waves-light btn white-text blue" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>AdventureJournal</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Lobster|Pacifico|Merriweather|Bree+Serif|Open+Sans|Righteous|Doppio+One' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js"></script>
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <main>
  <body>
    <header>
      <nav class="z-depth-0 navbar">
        <div class="nav-wrapper white lighten-4">
          <a href="/" class="brand-logo black-text center" id="navbar-branding">AdventureJournal</a>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><%= user_profile_path %></li>
            <li><%= login_logout_path %></li>
          </ul>
        </div>
      </nav>
    </header>
    <br>
    <% flash.each do |type, msg| %>
        <%= content_tag :div, sanitize(msg), class: " flash flash_#{type}" %>
    <% end %>
    <br>
    <%= yield %>
    <br>
    </main>​
    <footer class="page-footer white">
      <div class="footer-copyright">
        <div class="container">
          <a class="black-text text-lighten-4 left" href="https://github.com/acareaga" target="_blank">Made by Aaron Careaga</a>
          <div class= "black-text text-lighten-4 right">© 2015 AdventureJournal</div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/welcome/index.html.erb
<div class="row">
  <div class="col s12"><span class="flow-text">Hello, <%= current_user %> </span></div>
</div>